### ISSUE TITLE
Allow list to be filtered by params

### ISSUE THREAD

**Issue by andybotting** [NeCTAR-RC/python-nectarallocationclient#1]
Would be useful to allow the allocation list to be filtered. 

For example
  `openstack allocation list --property email=test@example.com`
or
  `openstack allocation list --property name=MyProjectName`

**Comment by brettmilford** [comment]
Docs, for the python api client usage would be helpful. I assume its something like
```python
client.allocations.list([{"key" : "value" },{"another_key" : "another_value"}])
```
