### ISSUE TITLE
Addition of CI field to the allocation object

### ISSUE THREAD

**Issue by brettmilford** [NeCTAR-RC/python-nectarallocationclient#3]
It would be highly beneficial to be able to access CI information alongside other allocation information.  So that, for instance:
```python
...
allocations = nectar.allocations.list()
for a in allocations:
    if "monash.edu" in a.ci_email:
        ...
```

**Comment by sorrison** [comment]
Fixed with https://github.com/NeCTAR-RC/nectar-dashboard/commit/7456a140da088c71a11941fafa9cfb1472dfba0b
